### ISSUE TITLE
Unauthorized use of Astro's Intellectual Property

### ISSUE THREAD

**Issue by natemoo-re** [gethyas/gethyas.com#304]
Hyas seems to take quite a lot of inspiration from [Astro](https://astro.build/)! We're glad you like the project, but this is a little too close for comfort for us.

**Comment by h-enk** [comment]
I get it — sorry about that! I will use a different design for gethyas.com

**Comment by natemoo-re** [comment]
Thanks, we'd really appreciate that! No need to keep the issue open, but best of luck.
